[jira]
token = "CHANGE--Insert-PAT"
base_url = "CHANGE--https://my-jira-domain.com"
server_api_v2 = "rest/api/2"
agile_api_v1 = "rest/agile/1.0"
greenhopper_api = "rest/greenhopper/1.0"

[log]
msg_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[retries]
tries = 10
delay = 0.0
backoff = 2

[requests]
timeout = 60

[concurrency]
semaphore_limit = 50

[pagination]
page_results = 40